---
name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  # We have to duplicate jobs since apparently secrets cannot be matrix
  # operations.

  test-encoded:
    runs-on: ubuntu-latest
    container: shellspec/shellspec:latest

    steps:
      - uses: actions/checkout@v3

      - run: "sed -i '/image:/s/: .*/: Dockerfile/' action.yaml"

      - uses: ./
        with:
          key_encoded: |
            AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIFCxz+W3/HMKpHM1da+6Dj9/
            P9esuJAuRm6Ie9KkIe02AAAABQAAAEBj19dRJ3RpTuTSsTOiWOviyEir3fEVwinDo8VplMzKbfWi
            7l3NLXVnWBfqy2bNr3SHLnNv0zlKa0dSIJ9YsWq9AAAAAA==

      - run: shellspec
