---
name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  # We have to duplicate jobs since apparently secrets cannot be matrix
  # operations.

  test-encoded:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make sure the container is built and not using a registry
        run: "sed -i '/image:/s/: .*/: Dockerfile/' action.yaml"

      - name: Run the current action
        uses: ./
        with:
          key_encoded: |
            AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIFCxz+W3/HMKpHM1da+6Dj9/
            P9esuJAuRm6Ie9KkIe02AAAABQAAAEBj19dRJ3RpTuTSsTOiWOviyEir3fEVwinDo8VplMzKbfWi
            7l3NLXVnWBfqy2bNr3SHLnNv0zlKa0dSIJ9YsWq9AAAAAA==

      - name: Run tests
        run: docker run --rm -t -v "${PWD}:/src" shellspec/shellspec:latest
